server:
  port: 8080

erpnext:
  base-url: https://sltallyautomation.m.erpnext.com/
  api-key:  29cdf452b42aeb0
  api-secret: 18a80c183d78a09

etf:
  auto-sell:
    profit-percent: 3.0

#    url: jdbc:postgresql://localhost:5432/sltallydb
#    username: postgres
#    password: $hiv@m2010
    
spring:
  datasource:
    url: jdbc:postgresql://ep-curly-waterfall-afoofohi-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require
    username: neondb_owner
    password: npg_12wBCUlQvpNc
    driver-class-name: org.postgresql.Driver

    hikari:
      maximum-pool-size: 5
      minimum-idle: 0              # ⭐ CRITICAL
      idle-timeout: 30000           # 30 sec
      max-lifetime: 60000           # 1 min
      connection-timeout: 30000
      keepalive-time: 0             # ⭐ CRITICAL
      initialization-fail-timeout: 0

  jpa:
    open-in-view: false             # ⭐ CRITICAL
    hibernate:
      ddl-auto: none                # ⭐ CRITICAL
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
